"""'add idempotency records'

Revision ID: 01b96d02ccc7
Revises: de3ce00bd136
Create Date: 2026-02-17 03:26:30.951720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01b96d02ccc7'
down_revision: Union[str, None] = 'de3ce00bd136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('idx_idempotency_expires', 'idempotency_records', ['expires_at'], unique=False)
    op.create_index('idx_idempotency_key', 'idempotency_records', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_idempotency_key', table_name='idempotency_records')
    op.drop_index('idx_idempotency_expires', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
