"""initial schema

Revision ID: de3ce00bd136
Revises: 
Create Date: 2026-02-17 01:31:59.129665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de3ce00bd136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('feature', 'bug', 'tech_debt', name='task_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('todo', 'doing', 'done', 'wont_do', name='status_enum'), server_default=sa.text("'todo'"), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sizing_confidence', sa.Integer(), nullable=True),
    sa.Column('needs_refinement', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('refinement_notes', sa.Text(), nullable=True),
    sa.Column('context_captured_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points >= 0 AND points <= 10', name='ck_tasks_points_range'),
    sa.CheckConstraint('sizing_confidence >= 0 AND sizing_confidence <= 5', name='ck_tasks_sizing_confidence_range'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_parent', 'tasks', ['parent_task_id'], unique=False)
    op.create_index('idx_tasks_points', 'tasks', ['points'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('task_commits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('committed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commits_task', 'task_commits', ['task_id'], unique=False)
    op.create_table('task_locks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('caller_label', sa.String(length=255), nullable=False),
    sa.Column('lock_purpose', sa.Enum('sizing', 'breakdown', 'refinement', 'implementation', name='lock_purpose_enum'), nullable=False),
    sa.Column('acquired_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_locks_expiry', 'task_locks', ['expires_at'], unique=False)
    op.create_index('idx_locks_task', 'task_locks', ['task_id'], unique=True)
    op.create_table('work_log_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('operation', sa.Enum('sizing', 'breakdown', 'refinement', 'implementation', 'note', name='operation_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worklog_task', 'work_log_entries', ['task_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_worklog_task', table_name='work_log_entries')
    op.drop_table('work_log_entries')
    op.drop_index('idx_locks_task', table_name='task_locks')
    op.drop_index('idx_locks_expiry', table_name='task_locks')
    op.drop_table('task_locks')
    op.drop_index('idx_commits_task', table_name='task_commits')
    op.drop_table('task_commits')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_points', table_name='tasks')
    op.drop_index('idx_tasks_parent', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('projects')
    op.execute("DROP TYPE IF EXISTS operation_enum")
    op.execute("DROP TYPE IF EXISTS lock_purpose_enum")
    op.execute("DROP TYPE IF EXISTS status_enum")
    op.execute("DROP TYPE IF EXISTS task_type_enum")
    # ### end Alembic commands ###
